// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	users "BE-Sosmed/features/users"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: token
func (_m *Service) DeleteUser(token *jwt.Token) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwt.Token) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserById provides a mock function with given fields: UserID
func (_m *Service) GetUserById(UserID uint) (users.User, error) {
	ret := _m.Called(UserID)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (users.User, error)); ok {
		return rf(UserID)
	}
	if rf, ok := ret.Get(0).(func(uint) users.User); ok {
		r0 = rf(UserID)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(UserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUsername provides a mock function with given fields: username
func (_m *Service) GetUserByUsername(username string) (users.User, error) {
	ret := _m.Called(username)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (users.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) users.User); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: email, password
func (_m *Service) Login(email string, password string) (users.User, error) {
	ret := _m.Called(email, password)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (users.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) users.User); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutUser provides a mock function with given fields: token, updatedUser
func (_m *Service) PutUser(token *jwt.Token, updatedUser users.User) (users.User, error) {
	ret := _m.Called(token, updatedUser)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, users.User) (users.User, error)); ok {
		return rf(token, updatedUser)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, users.User) users.User); ok {
		r0 = rf(token, updatedUser)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, users.User) error); ok {
		r1 = rf(token, updatedUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: newUser
func (_m *Service) Register(newUser users.User) (users.User, error) {
	ret := _m.Called(newUser)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(users.User) (users.User, error)); ok {
		return rf(newUser)
	}
	if rf, ok := ret.Get(0).(func(users.User) users.User); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(users.User) error); ok {
		r1 = rf(newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
